### ISSUE TITLE
Bug: Snapping Feature does not work in multiplayer

### ISSUE THREAD

**Issue by Timmeey86** [Timmeey86/FS22_ForestryHelper#18]
This is because only the client knows where to cut. This information needs to be transferred to the server through an event whenever the chainsaw's snap state changes.

A first approach would be to create a `ChainsawSnapStateChangeEvent`and send that to the server whenever the state changes on a client.
The event would contain the shape ID, the snap state and the cut location.
The server could then adjust the cut location accordingly.

This would however fail in the following scenario:
1. Player A snaps their chainsaw to the shape
2. Player B aims at the shape, but does not snap
3. Player A cuts the tree

=> The server would not adjust the cut location since the method used for cutting doesn't have any information about which player sent the cut event

It would be possible to transfer more information with the cut event, but it is being sent in a deeply nested block, therefore increasing the chance of things breaking with the next game update.

**Comment by Achimobil** [comment]
Will that be fixed in the FS22 Version or not?

**Comment by Timmeey86** [comment]
So far I haven't managed to synchronise it properly. I might look into it again now that I have more experience in how that works.

**Comment by Achimobil** [comment]
Sounds good. I tested the mod in SP and the marking and locking of the chainsaw is great for woodworking. I was very disappointed when it didn't work on the server. If I can help in any way, you know how to contact me ;)

**Comment by Timmeey86** [comment]
> Sounds good. I tested the mod in SP and the marking and locking of the chainsaw is great for woodworking. I was very disappointed when it didn't work on the server. If I can help in any way, you know how to contact me ;)

Probier' mal das [neue Release](https://github.com/Timmeey86/FS22_ForestryHelper/releases/tag/v1.0.5.5)

**Comment by Achimobil** [comment]
Sehr geil. Getestet auf dem Server und funktioniert wie im Single Player.
Danke dafür.
