### ISSUE TITLE
Add Chainsaw cut duration...

### ISSUE THREAD

**Issue by FirenzeIT** [Timmeey86/FS22_ForestryHelper#24]
Hello @Timmeey86, it's possible add the option as a title mentioned inside this mod? I know the Lumberjack's mod have this, but i would use your mod... In this case, this mod has more realistic 👍🏻

**Comment by Timmeey86** [comment]
Hi, I won't integrate features of other existing mods into my mod (unless I don't know about the other mod, of course).
Lumberjack has many settings so you could set it up to just have a different cut duration, but disable super strength etc.
Both mods are compatible with one another

**Comment by FirenzeIT** [comment]
Hi, ah ok it's compatible both in same time?

Il Mar 8 Ott 2024, 14:59 Timmeey86 ***@***.***> ha scritto:

**Comment by Timmeey86** [comment]
Yes, they do different things so they can be used together
